apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-pets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: copy-files
          image: busybox:latest
          command: ['sh', '-c', 'cp -r /shared/frontend/* /usr/share/nginx/html/ && echo "Frontend files copied successfully"']
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
            - name: frontend-files
              mountPath: /usr/share/nginx/html
      containers:
        - name: frontend
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-files
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: frontend-files
          emptyDir: {}
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-storage
        - name: nginx-config
          configMap:
            name: nginx-config
